//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coopors.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoltState
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Holt_State { get; set; }
        public string PageName { get; set; }
    }
}
