//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coopors.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestion
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public int Assessment { get; set; }
        public string ChekBoxId { get; set; }
    }
}
