//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coopors.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReport
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Assessment { get; set; }
        public string ReportFile { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
